import {AbsoluteFill} from 'remotion';
import type {ComponentProps, ComponentType} from 'react';
import type {Control} from './controls';
import type {PreviewProps as Props} from './types';
import {range, color, select, booleanControl, numberControl} from './controls';
import {FisheyePreview, fisheyePreviewDefaults} from './fisheye';
import {VhsPreview, vhsPreviewDefaults} from './vhs';
import {
	Waveform,
	Spectre,
	Oscilloscope,
	Pulsar,
	Circle,
	Halo,
	AudioParticles,
	Ferrofluid,
	Trip,
	Space,
	Synthwave,
	Mushrooms,
	Fractals,
	Hyperloop,
	Downfall,
	Rail,
	Rain,
	Kaleidoscope,
	Eye,
	Flowers,
	Moon,
	City,
	Basic,
} from '../../../../../packages/elements/dist/components';

type PreviewExample<C extends ComponentType<Props>> = {
	component: C;
	width: number;
	height: number;
	props: Partial<ComponentProps<C>>;
	controls: readonly Control<Extract<keyof ComponentProps<C>, string>>[];
};

const DEFAULT_AUDIO = 'https://remotion.media/elements/remotion-made-this-picture-move.mp3';
const HALO_AUDIO =
	'https://raw.githubusercontent.com/remotion-dev/remotion/main/packages/template-music-visualization/public/demo-track.mp3';
const AUDIO_PARTICLES_AUDIO =
	'https://raw.githubusercontent.com/remotion-dev/remotion/main/packages/template-recorder/public/sounds/utope-rhythmic-reverie.mp3';
const colorMode = select('colorMode', 'Color mode', [
	{value: 'gradient', label: 'Gradient'},
	{value: 'rainbow', label: 'Rainbow'},
]);
const gain = range('inputGainDb', 'Visual gain', -30, 30, 1);
const intensity = range('intensity', 'Intensity', 0.1, 10, 0.1);

const HaloAndParticles = (props: Props) => {
	const audioSrc = String(props.audioSrc ?? AUDIO_PARTICLES_AUDIO);
	const audioOffsetInSeconds = Number(props.audioOffsetInSeconds ?? 0);
	return (
		<AbsoluteFill style={{backgroundColor: '#080a10'}}>
			<AbsoluteFill>
				<Halo
					audioSrc={audioSrc}
					audioOffsetInSeconds={audioOffsetInSeconds}
					playAudio={Boolean(props.playAudio ?? true)}
					intensity={1}
					inputGainDb={0}
					radius={0.12}
					trailDepth={9}
				/>
			</AbsoluteFill>
			<AbsoluteFill>
				<AudioParticles
					audioSrc={audioSrc}
					audioOffsetInSeconds={audioOffsetInSeconds}
					playAudio={false}
					width={1280}
					height={720}
					maskHalo
					inputGainDb={0}
					intensity={1}
					radius={0.12}
					density={45}
					size={1.5}
				/>
			</AbsoluteFill>
		</AbsoluteFill>
	);
};
export const examples = {
	vhs: {
		component: VhsPreview,
		width: 1280,
		height: 720,
		props: vhsPreviewDefaults,
		controls: [
			range('strength', 'Effect strength / bypass', 0, 1, 0.01),
			range('horizontalDistortion', 'Horizontal distortion', 0.005, 0.07, 0.001),
			range('glitch', 'Fine tape jitter', 0.01, 0.07, 0.01),
			range('line', 'Tracking band', 0.01, 1, 0.01),
			range('period', 'Tracking speed', 0.01, 2, 0.01),
			numberControl('timeOffsetInSeconds', 'Effect phase (s)', -86400, 86400, 0.01),
		],
	} satisfies PreviewExample<typeof VhsPreview>,
	fisheye: {
		component: FisheyePreview,
		width: 1280,
		height: 720,
		props: fisheyePreviewDefaults,
		controls: [
			range('strength', 'Distortion strength / bypass', 0, 2, 0.01),
			range('perspectiveFactor', 'Perspective compensation', 0, 1, 0.01),
		],
	} satisfies PreviewExample<typeof FisheyePreview>,
	fractals: {
		component: Fractals,
		width: 1280,
		height: 720,
		props: {
			baseColor: '#ff00ff',
			mixColor: '#9333ea',
			pulsating: 6.28318,
			zoom: 1.5,
			pattern: 8,
			responsive: 1,
			inputGainDb: 0,
		},
		controls: [
			color('baseColor', 'Base color'),
			color('mixColor', 'Mix color'),
			range('pulsating', 'Pulsating', 2, 60, 0.5),
			range('zoom', 'Zoom', 0.25, 3.5, 0.25),
			range('pattern', 'Pattern', 0.5, 50, 0.5),
			range('responsive', 'Audio reactivity', 0, 10, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Fractals>,
	hyperloop: {
		component: Hyperloop,
		width: 1280,
		height: 720,
		props: {
			baseColor: '#9333ea',
			volume: 0.15,
			depth: 4,
			speed: 2,
			rotationSpeed: 2.3,
			pattern: 1,
			responsive: 2,
			inputGainDb: 0,
		},
		controls: [
			color('baseColor', 'Base color'),
			range('volume', 'Volume', 0.05, 10.5, 0.1),
			range('depth', 'Depth', 1, 50, 0.5),
			range('speed', 'Speed', 0.5, 4, 0.25),
			range('rotationSpeed', 'Rotation speed', 1, 20, 0.25),
			range('pattern', 'Pattern', 1, 3, 0.01),
			range('responsive', 'Audio reactivity', 0, 50, 0.5),
			gain,
		],
	} satisfies PreviewExample<typeof Hyperloop>,
	downfall: {
		component: Downfall,
		width: 1280,
		height: 720,
		props: {
			startColor: '#9333ea',
			endColor: '#ff00ff',
			textureScale: 1,
			textureRotation: 1,
			variant: 1,
			bloating: 1,
			intensity: 1,
			bpm: 120,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Base color'),
			color('endColor', 'Mix color'),
			range('textureScale', 'Texture scale', 0.5, 20, 0.5),
			range('textureRotation', 'Texture rotation', 0, 180, 1),
			range('variant', 'Variant', 1, 3, 1),
			range('bloating', 'Bloating', 1, 10, 0.5),
			range('intensity', 'Intensity', 1, 50, 0.5),
			range('bpm', 'Tempo (BPM)', 1, 300, 1),
			gain,
		],
	} satisfies PreviewExample<typeof Downfall>,
	kaleidoscope: {
		component: Kaleidoscope,
		width: 1280,
		height: 720,
		props: {
			startColor: '#877d87',
			scale: 5,
			responsive: 0.3,
			randomColors: false,
			disableMovement: false,
			still: false,
			speed: 0.1,
			pattern: 3,
			amount: 1.5,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Theme color'),
			booleanControl('randomColors', 'Random colors'),
			booleanControl('disableMovement', 'Disable movement'),
			booleanControl('still', 'Still pattern'),
			range('scale', 'Scale', 1, 10, 0.5),
			range('speed', 'Movement speed', 0.1, 10, 0.1),
			range('pattern', 'Pattern', 0.5, 10, 0.5),
			range('amount', 'Amount', 0.5, 15, 0.5),
			range('responsive', 'Audio reactivity', 0, 4, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Kaleidoscope>,
	eye: {
		component: Eye,
		width: 1280,
		height: 720,
		props: {
			startColor: '#0f5f7a',
			endColor: '#db0791',
			responsive: 1.5,
			speed: 1,
			dark: false,
			colorful: false,
			volume: 0.5,
			amount: 50,
			smoothness: 27,
			bpm: 120,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Theme color'),
			color('endColor', 'Second color'),
			booleanControl('dark', 'Dark mode'),
			booleanControl('colorful', 'Colorful mode'),
			range('volume', 'Volume', 0.1, 10, 0.1),
			range('amount', 'Amount', 1, 70, 1),
			range('smoothness', 'Smoothness', 1, 100, 1),
			range('speed', 'Speed', 0.1, 2, 0.01),
			range('bpm', 'Tempo (BPM)', 1, 300, 1),
			range('responsive', 'Audio reactivity', 0, 6, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Eye>,
	flowers: {
		component: Flowers,
		width: 1280,
		height: 720,
		props: {
			strokeColor: '#a1a1a1',
			backgroundColor: '#000000',
			scale: 15,
			responsive: 1,
			rotationSpeed: 1,
			flowersSpeed: 0.2,
			volume: 3,
			pattern: 2,
			inputGainDb: 0,
		},
		controls: [
			color('strokeColor', 'Stroke color'),
			color('backgroundColor', 'Background color'),
			range('scale', 'Scale', 2, 30, 0.5),
			range('pattern', 'Pattern', 0.1, 2, 0.1),
			range('volume', 'Volume', 1, 4, 0.5),
			range('rotationSpeed', 'Rotation speed', 0.1, 10, 0.1),
			range('flowersSpeed', 'Flowers speed', 0.1, 3, 0.1),
			range('responsive', 'Audio reactivity', 0.1, 2.7, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Flowers>,
	moon: {
		component: Moon,
		width: 1280,
		height: 720,
		props: {
			startColor: '#c21aff',
			moonColor: '#000000',
			responsive: 1.3,
			hideMoon: false,
			hideAudio: false,
			stars: 6,
			pattern: 0.25,
			speed: 0.25,
			volume: 0.5,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Theme color'),
			color('moonColor', 'Moon color'),
			booleanControl('hideMoon', 'Hide moon'),
			booleanControl('hideAudio', 'Hide spectrum'),
			range('stars', 'Stars density', 1, 60, 1),
			range('pattern', 'Flickering', 0.1, 5, 0.05),
			range('speed', 'Movement speed', 0.1, 2, 0.1),
			range('volume', 'Volume', 0.1, 2, 0.1),
			range('responsive', 'Audio reactivity', 0, 4, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Moon>,
	city: {
		component: City,
		width: 1280,
		height: 720,
		props: {
			startColor: '#324952',
			endColor: '#001361',
			lightsColor: '#f5fff7',
			groundColor: '#0cb8cf',
			shineColor: '#949494',
			responsive: 1,
			stars: 1,
			speed: 1,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Theme color'),
			color('endColor', 'Sky shine color'),
			color('lightsColor', 'Lights color'),
			color('groundColor', 'Grid color'),
			color('shineColor', 'Grid shine color'),
			range('stars', 'Stars density', 0.1, 5, 0.1),
			range('speed', 'Speed', 0, 20, 0.25),
			range('responsive', 'Audio reactivity', 0.1, 10, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof City>,
	basic: {
		component: Basic,
		width: 1280,
		height: 720,
		props: {
			backgroundColor: '#070c22',
			intensifyColor: '#221d49',
			starsColor: '#858585',
			responsive: 1.3,
			enableStars: true,
			starsAudioReactivity: 1,
			stars: 6,
			pattern: 0.25,
			speed: 1,
			inputGainDb: 0,
		},
		controls: [
			color('backgroundColor', 'Background color'),
			color('intensifyColor', 'Intensify color'),
			color('starsColor', 'Stars color'),
			booleanControl('enableStars', 'Enable stars'),
			range('stars', 'Stars density', 1, 60, 1),
			range('pattern', 'Flickering', 0.1, 5, 0.05),
			range('speed', 'Movement speed', 0, 10, 0.1),
			range('starsAudioReactivity', 'Stars audio reactivity', 1, 40, 0.5),
			range('responsive', 'Audio reactivity', 0, 4, 0.1),
			gain,
		],
	} satisfies PreviewExample<typeof Basic>,
	rail: {
		component: Rail,
		width: 1280,
		height: 720,
		props: {
			startColor: '#877d87',
			endColor: '#c800ff',
			sunPosition: 0.02,
			sunSize: 0,
			volume: 0.25,
			sides: 35,
			waves: 0.15,
			intensity: 20,
			stroke: 0.001,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Theme'),
			color('endColor', 'Sky color'),
			range('sunPosition', 'Sun position', 0, 0.5, 0.01),
			range('sunSize', 'Sun size', -4, 2, 0.25),
			range('volume', 'Volume', 0.1, 0.5, 0.01),
			range('sides', 'Sides', 1, 50, 0.5),
			range('waves', 'Waves', 0, 0.35, 0.01),
			range('intensity', 'Intensity', 1, 50, 0.5),
			range('stroke', 'Stroke', 0.001, 0.005, 0.0001),
			gain,
		],
	} satisfies PreviewExample<typeof Rail>,
	rain: {
		component: Rain,
		width: 1280,
		height: 720,
		props: {textureScale: 3.5, distancing: 2.5, blur: 0.9, intensity: 3, inputGainDb: 0},
		controls: [
			range('textureScale', 'Background scale', 0.5, 20, 0.5),
			range('distancing', 'Distancing', 0, 3, 0.1),
			range('blur', 'Blur', 0.2, 1, 0.1),
			range('intensity', 'Thunderstorm', 0, 7, 0.5),
			gain,
		],
	} satisfies PreviewExample<typeof Rain>,
	space: {
		component: Space,
		width: 1280,
		height: 720,
		props: {
			baseColor: '#ff00ff',
			zoom: 0.8,
			stellarDensity: 17,
			pattern: 0.54,
			speed: 0.01,
			responsive: 1,
			timeOffsetInSeconds: 0,
			inputGainDb: 0,
		},
		controls: [
			color('baseColor', 'Base color'),
			range('zoom', 'Zoom', 0.1, 3, 0.1),
			range('stellarDensity', 'Stellar density', 5, 25, 1),
			range('pattern', 'Pattern', 0.46, 0.58, 0.005),
			range('speed', 'Speed', 0.001, 0.04, 0.001),
			range('responsive', 'Audio reactivity', 0.5, 3, 0.25),
			numberControl('timeOffsetInSeconds', 'Animation offset (s)', 0, 86400, 0.01),
			gain,
		],
	} satisfies PreviewExample<typeof Space>,
	synthwave: {
		component: Synthwave,
		width: 1280,
		height: 720,
		props: {
			startColor: '#9333ea',
			endColor: '#ff00ff',
			sphereColor: '#4b9dc3',
			hideSphere: false,
			mountainsPattern: 1,
			mountainsHeight: 4,
			mountainsSmoothness: 1,
			mountainsDistance: 0,
			responsive: 1,
			bpm: 120,
			timeOffsetInSeconds: 0,
			inputGainDb: 0,
		},
		controls: [
			color('startColor', 'Base color'),
			color('endColor', 'Mountain outline'),
			color('sphereColor', 'Sphere color'),
			booleanControl('hideSphere', 'Hide sphere'),
			range('mountainsPattern', 'Mountains pattern', 1, 100, 0.5),
			range('mountainsHeight', 'Mountains height', 1, 10, 0.5),
			range('mountainsSmoothness', 'Mountains smoothness', 1, 10, 0.5),
			range('mountainsDistance', 'Mountains distance', -10, 10, 0.5),
			range('responsive', 'Audio reactivity', 1, 10, 1),
			range('bpm', 'Tempo (BPM)', 1, 300, 1),
			numberControl('timeOffsetInSeconds', 'Animation offset (s)', 0, 86400, 0.01),
			gain,
		],
	} satisfies PreviewExample<typeof Synthwave>,
	mushrooms: {
		component: Mushrooms,
		width: 1280,
		height: 720,
		props: {
			baseColor: '#ff00ff',
			mixColor: '#9333ea',
			colorful: 0,
			contrast: 6,
			cubeScale: 1,
			responsive: 0,
			timeOffsetInSeconds: 0,
			inputGainDb: 0,
		},
		controls: [
			color('baseColor', 'Base color'),
			color('mixColor', 'Mix color'),
			range('colorful', 'Colorful', -2, 12, 0.5),
			range('contrast', 'Contrast', 1, 9, 0.5),
			range('cubeScale', 'Cube scale', 0.5, 2, 0.25),
			range('responsive', 'Audio reactivity', -10, 30, 0.5),
			numberControl('timeOffsetInSeconds', 'Animation offset (s)', 0, 86400, 0.01),
			gain,
		],
	} satisfies PreviewExample<typeof Mushrooms>,
	trip: {
		component: Trip,
		width: 1280,
		height: 720,
		props: {
			baseColor: '#ff00ff',
			intensifyColor: '#9333ea',
			thickness: 1,
			pattern: 0.7,
			intensity: 10,
			bpm: 120,
			timeOffsetInSeconds: 0,
			inputGainDb: 0,
		},
		controls: [
			color('baseColor', 'Base color'),
			color('intensifyColor', 'Intensify color'),
			// A native range with min 0.01 / step 0.05 silently snaps the source default 1 to 1.01.
			range('thickness', 'Thickness', 0.01, 1.5, 0.01),
			range('pattern', 'Pattern', 0.7, 9, 0.25),
			range('intensity', 'Raymarch intensity', 0, 25, 0.5),
			range('bpm', 'Tempo (BPM)', 1, 300, 1),
			numberControl('timeOffsetInSeconds', 'Animation offset (s)', 0, 86400, 0.01),
			gain,
		],
	} satisfies PreviewExample<typeof Trip>,
	ferrofluid: {
		component: Ferrofluid,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 10,
			intensity: 2,
			pattern: 2,
			fluidity: 0.15,
			color: '#161923',
			shineColor: '#ffbc8e',
			shineX: -0.3,
			shineY: -1,
			shineZ: -0.5,
			shineIntensity: 2.6,
			shineSize: 1,
			roughness: 0.15,
			iridescence: 0.3,
			envMapIntensity: 1,
			audioLights: true,
			quality: 'medium',
			mappingMode: 'uniform',
			autoRotate: true,
			rotationSpeed: 1,
		},
		controls: [
			color('color', 'Metal tint'),
			color('shineColor', 'Shine color'),
			range('shineX', 'Shine X', -3, 3, 0.1),
			range('shineY', 'Shine Y', -3, 3, 0.1),
			range('shineZ', 'Shine Z', -3, 3, 0.1),
			range('shineIntensity', 'Shine intensity', 0, 10, 0.1),
			range('shineSize', 'Shine size', 0.1, 3, 0.1),
			gain,
			range('intensity', 'Intensity', 0.1, 12, 0.1),
			range('pattern', 'Spike density', 1, 20, 0.1),
			range('fluidity', 'Fluidity', 0, 1, 0.01),
			range('roughness', 'Roughness', 0, 1, 0.01),
			range('iridescence', 'Iridescence', 0, 1, 0.01),
			range('envMapIntensity', 'Studio reflections', 0, 2, 0.01),
			select('quality', 'Quality', [
				{value: 'low', label: 'Low'},
				{value: 'medium', label: 'Medium'},
				{value: 'high', label: 'High'},
			]),
			select('mappingMode', 'Frequency mapping', [
				{value: 'uniform', label: 'Uniform'},
				{value: 'latitude', label: 'Latitude'},
				{value: 'radial', label: 'Radial'},
				{value: 'voronoi', label: 'Voronoi'},
			]),
			booleanControl('audioLights', 'Audio-reactive lights'),
			booleanControl('autoRotate', 'Auto rotate'),
			range('rotationSpeed', 'Rotation speed', -3, 3, 0.1),
		],
	} satisfies PreviewExample<typeof Ferrofluid>,
	waveform: {
		component: Waveform,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 1.6,
			color: '#b794ff',
			windowInSeconds: 2,
		},
		controls: [
			color('color', 'Color'),
			gain,
			intensity,
			range('windowInSeconds', 'Time window', 0.1, 5, 0.1),
		],
	} satisfies PreviewExample<typeof Waveform>,
	spectre: {
		component: Spectre,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			startColor: '#3373d4',
			endColor: '#f567f5',
			colorMode: 'gradient',
			count: 64,
			barWidth: 3,
			bottom: false,
			spectreVariant: 'bars',
		},
		controls: [
			select('spectreVariant', 'Treatment', [
				{value: 'bars', label: 'Bars'},
				{value: 'segmented', label: 'Segmented'},
			]),
			colorMode,
			color('startColor', 'Start color'),
			color('endColor', 'End color'),
			gain,
			intensity,
			range('count', 'Bar count', 5, 150, 1),
			range('barWidth', 'Bar width', 0.5, 10, 0.5),
			booleanControl('bottom', 'Align to bottom'),
		],
	} satisfies PreviewExample<typeof Spectre>,
	segmented: {
		component: Spectre,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			startColor: '#3373d4',
			endColor: '#f567f5',
			colorMode: 'gradient',
			count: 64,
			barWidth: 3,
			bottom: false,
			spectreVariant: 'segmented',
		},
		controls: [],
	} satisfies PreviewExample<typeof Spectre>,
	oscilloscope: {
		component: Oscilloscope,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			amplitude: 1.5,
			lineColor: '#51e8cc',
			lineWidth: 3,
			sampleCount: 1024,
		},
		controls: [
			color('lineColor', 'Line color'),
			gain,
			range('amplitude', 'Amplitude', 0.1, 10, 0.1),
			range('lineWidth', 'Line width', 0.5, 10, 0.5),
			select('sampleCount', 'PCM samples', [
				{value: '256', label: '256'},
				{value: '512', label: '512'},
				{value: '1024', label: '1024'},
				{value: '2048', label: '2048'},
			]),
		],
	} satisfies PreviewExample<typeof Oscilloscope>,
	pulsar: {
		component: Pulsar,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 1,
			intensity: 1,
			density: 1.5,
			pattern: 4,
			volume: 2,
			startColor: '#592bb3',
			endColor: '#195753',
			colorMode: 'gradient',
		},
		controls: [
			colorMode,
			color('startColor', 'Start color'),
			color('endColor', 'End color'),
			gain,
			intensity,
			range('density', 'Density', 0.1, 5, 0.1),
			range('pattern', 'Pattern', 0.5, 16, 0.5),
			range('volume', 'Volume size', 0.5, 10, 0.5),
		],
	} satisfies PreviewExample<typeof Pulsar>,
	circle: {
		component: Circle,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			radius: 0.46,
			count: 64,
			lineWidth: 3,
			startColor: '#b794ff',
			endColor: '#51e8cc',
			colorMode: 'gradient',
			circleVariant: 'radial-bars',
		},
		controls: [
			select('circleVariant', 'Treatment', [
				{value: 'radial-bars', label: 'Radial bars'},
				{value: 'glow-ring', label: 'Glow ring'},
				{value: 'waveform-ring', label: 'Waveform ring'},
				{value: 'dotted-ring', label: 'Dotted ring'},
			]),
			colorMode,
			color('startColor', 'Start color'),
			color('endColor', 'End color'),
			gain,
			intensity,
			range('radius', 'Radius', 0.05, 0.8, 0.01),
			range('count', 'Count', 5, 150, 1),
			range('lineWidth', 'Line / dot width', 0.5, 10, 0.5),
		],
	} satisfies PreviewExample<typeof Circle>,
	glow: {
		component: Circle,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			radius: 0.46,
			circleVariant: 'glow-ring',
		},
		controls: [],
	} satisfies PreviewExample<typeof Circle>,
	'ring-waveform': {
		component: Circle,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			radius: 0.46,
			circleVariant: 'waveform-ring',
		},
		controls: [],
	} satisfies PreviewExample<typeof Circle>,
	dotted: {
		component: Circle,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 4,
			intensity: 4,
			radius: 0.46,
			circleVariant: 'dotted-ring',
			count: 48,
			lineWidth: 1,
		},
		controls: [],
	} satisfies PreviewExample<typeof Circle>,
	halo: {
		component: Halo,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 0,
			intensity: 1,
			radius: 0.12,
			trailDepth: 9,
			waveDelay: true,
			motionBlur: true,
			glowBlur: 0,
			glowSpread: 0,
			colorMode: 'rainbow',
			startColor: '#aa8bff',
			endColor: '#51e8cc',
			centerColor: '#2d2d2d',
			centerMode: 'filled',
			artworkSrc: '',
		},
		controls: [
			colorMode,
			color('startColor', 'Gradient start color'),
			color('endColor', 'Gradient end color'),
			color('leadingColor', 'Leading edge'),
			select('centerMode', 'Center mode', [
				{value: 'filled', label: 'Filled'},
				{value: 'transparent', label: 'Transparent'},
			]),
			color('centerColor', 'Center color'),
			gain,
			intensity,
			range('radius', 'Radius', 0.05, 0.8, 0.01),
			range('trailDepth', 'Trail layers', 1, 9, 1),
			booleanControl('waveDelay', 'Delayed trails'),
			booleanControl('motionBlur', 'Temporal afterglow'),
			range('glowBlur', 'Glow blur', 0, 100, 1),
			range('glowSpread', 'Glow spread', 0, 100, 1),
		],
	} satisfies PreviewExample<typeof Halo>,
	'audio-particles': {
		component: AudioParticles,
		width: 1280,
		height: 720,
		props: {
			inputGainDb: 22,
			intensity: 7.4,
			radius: 0.2,
			density: 45,
			size: 1.5,
			startTimeInSeconds: -5,
			reactiveSpeed: true,
			maskHalo: false,
			color: '#b794ff',
		},
		controls: [
			color('color', 'Particle color'),
			gain,
			intensity,
			range('radius', 'Inner radius', 0.05, 0.8, 0.01),
			range('density', 'Density', 0, 50, 1),
			range('size', 'Particle size', 0.25, 2, 0.25),
			range('startTimeInSeconds', 'Emission start (s)', -5, 10, 0.01),
			booleanControl('reactiveSpeed', 'Bass-reactive speed'),
			booleanControl('maskHalo', 'Mask Halo edge'),
		],
	} satisfies PreviewExample<typeof AudioParticles>,
	combined: {
		component: HaloAndParticles,
		width: 1280,
		height: 720,
		props: {},
		controls: [],
	} satisfies PreviewExample<typeof HaloAndParticles>,
} as const;
export type PreviewKind = keyof typeof examples;
export const defaultAudioFor = (kind: PreviewKind) => {
	if (
		[
			'vhs',
			'fisheye',
			'halo',
			'ferrofluid',
			'trip',
			'space',
			'synthwave',
			'mushrooms',
			'fractals',
			'hyperloop',
			'downfall',
			'rail',
			'rain',
			'kaleidoscope',
			'eye',
			'flowers',
			'moon',
			'city',
			'basic',
		].includes(kind)
	)
		return HALO_AUDIO;
	if (kind === 'audio-particles' || kind === 'combined') return AUDIO_PARTICLES_AUDIO;
	return DEFAULT_AUDIO;
};
